In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
url = 'https://raw.githubusercontent.com/Naivedh/DS_Solution/master/Movie%20rating/Train.csv'
url1 = 'https://raw.githubusercontent.com/Naivedh/DS_Solution/master/Movie%20rating/Test.csv'

In [3]:
dataset = pd.read_csv(url)
dataset1 = pd.read_csv(url1)

In [4]:
dataset.shape

(40000, 2)

In [5]:
dataset1.shape

(10000, 1)

In [6]:
dataset.head()

review label
0  mature intelligent and highly charged melodram...   pos
1  http://video.google.com/videoplay?docid=211772...   pos
2  Title: Opera (1987) Director: Dario Argento Ca...   pos
3  I think a lot of people just wrote this off as...   pos
4  This is a story of two dogs and a cat looking ...   pos

In [7]:
dataset['label'].value_counts()

pos    20011
neg    19989
Name: label, dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le = LabelEncoder()

In [10]:
y= dataset['label'].values

In [11]:
y = le.fit_transform(y)

In [12]:
y[:100]

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0])

In [13]:
dataset['review']

0        mature intelligent and highly charged melodram...
1        http://video.google.com/videoplay?docid=211772...
2        Title: Opera (1987) Director: Dario Argento Ca...
3        I think a lot of people just wrote this off as...
4        This is a story of two dogs and a cat looking ...
                               ...                        
39995    There are similarities between Ray Lawrence's ...
39996    For starters, I once met the director when he ...
39997    Much of "Over Her Dead Body" is so painfully u...
39998    "Lifeforce" is a truly bizarre adaptation of t...
39999    I saw this movie at a screener and its the bes...
Name: review, Length: 40000, dtype: object

**Pre-Processing**

In [14]:
import re
# import nltk
# nltk.download("popular")
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [15]:
sw = set(stopwords.words('english'))
ps = PorterStemmer()

In [16]:
def clean_text(sample):
    sample = sample.lower()
    sample = sample.replace("<br /><br />", "")
    sample = re.sub("[^a-z]+", " ", sample)
    
    sample = sample.split()
    
    sample =[ps.stem(s) for s in sample if s not in sw ] 

    sample = " ".join(sample)
    return sample

In [17]:
clean_text(dataset['review'][11])

'robert jordan televis star robert jordan like thing orderli time properli execut world children seen heard would mr jordan want becom master rambuncti band boy scout rate staff figur learn interact youth inclin watch show cours watch jordan cope compris fun like mr belveder mr belveder goe colleg one sure pleas anyon interest obtain copi film pleas write iamas yahoo com'

In [18]:
dataset['clean_review']=dataset['review'].apply(clean_text)

In [19]:
corpus = dataset['clean_review'].values

In [20]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

In [21]:
cv = CountVectorizer(max_df = 0.5, max_features= 3500)

In [22]:
X = cv.fit_transform(corpus)

In [23]:
print(X.shape)

(40000, 3500)


In [24]:
print(X[0])

  (0, 1948)	1
  (0, 1630)	1
  (0, 1474)	1
  (0, 505)	1
  (0, 1966)	1
  (0, 532)	1
  (0, 3006)	2
  (0, 2270)	1
  (0, 1872)	1
  (0, 2811)	1
  (0, 2723)	1
  (0, 1896)	1
  (0, 3077)	1


In [25]:
# between 0-1
tfidf =TfidfTransformer()

In [26]:
X = tfidf.fit_transform(X)

In [27]:
print(X[0])

  (0, 3077)	0.14054637872723058
  (0, 3006)	0.5461845598008374
  (0, 2811)	0.2015416230298577
  (0, 2723)	0.10665936533251619
  (0, 2270)	0.15343712651809796
  (0, 1966)	0.318678453679357
  (0, 1948)	0.30871978476235773
  (0, 1896)	0.2922586660359705
  (0, 1872)	0.13173360428110867
  (0, 1630)	0.2409100233619149
  (0, 1474)	0.2245852534003864
  (0, 532)	0.33395803795739487
  (0, 505)	0.29454043017953596


In [28]:
X.shape

(40000, 3500)

In [29]:
y.shape

(40000,)

In [30]:
dataset1['review']

0       Remember those old kung fu movies we used to w...
1       This movie is another one on my List of Movies...
2       How in the world does a thing like this get in...
3       "Queen of the Damned" is one of the best vampi...
4       The Caprica episode (S01E01) is well done as a...
                              ...                        
9995    Watched this piece ONDEMAND because the descri...
9996    A nurse travels to a rural psychiatric clinic ...
9997    Although this small film kind of got lost in t...
9998    I first saw this film in the early 80's on cab...
9999    Recognizing the picture of the diner on the co...
Name: review, Length: 10000, dtype: object

In [31]:
dataset1['clean_review']=dataset1['review'].apply(clean_text)

In [32]:
X_test = dataset1['clean_review']

In [33]:
X_test.shape

(10000,)

In [34]:
X_test = cv.transform(X_test)

In [35]:
X_test.shape

(10000, 3500)

In [36]:
X_test = tfidf.fit_transform(X_test)

In [37]:
print(X_test.shape)

(10000, 3500)


In [38]:
X = X.toarray()

In [39]:
X_test =X_test.toarray()

In [40]:
y_pred = []

In [41]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [42]:
X_test

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.1226264 , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.17841093,
        0.        ]])

In [43]:
wer

In [44]:
y_pred

array([0, 0, 0, ..., 1, 1, 0])

In [45]:
y_pred[y_pred>=0.5] = 1

In [46]:
y_pred[1]

0

In [47]:
dic = {0: 'neg', 1:'pos'}


In [48]:
y_pred = [dic[p] for p in y_pred]

In [49]:
y_pred

['neg',
 'neg',
 'neg',
 'pos',
 'pos',
 'neg',
 'pos',
 'neg',
 'pos',
 'pos',
 'pos',
 'pos',
 'pos',
 'neg',
 'neg',
 'pos',
 'neg',
 'pos',
 'pos',
 'neg',
 'neg',
 'pos',
 'neg',
 'neg',
 'neg',
 'neg',
 'neg',
 'pos',
 'neg',
 'pos',
 'pos',
 'neg',
 'neg',
 'neg',
 'pos',
 'pos',
 'neg',
 'neg',
 'neg',
 'neg',
 'neg',
 'pos',
 'pos',
 'neg',
 'neg',
 'neg',
 'pos',
 'pos',
 'pos',
 'pos',
 'neg',
 'neg',
 'pos',
 'neg',
 'pos',
 'neg',
 'pos',
 'pos',
 'neg',
 'pos',
 'neg',
 'pos',
 'neg',
 'pos',
 'neg',
 'neg',
 'neg',
 'neg',
 'pos',
 'pos',
 'pos',
 'pos',
 'neg',
 'pos',
 'pos',
 'pos',
 'pos',
 'pos',
 'pos',
 'pos',
 'pos',
 'neg',
 'pos',
 'pos',
 'pos',
 'pos',
 'neg',
 'pos',
 'neg',
 'pos',
 'neg',
 'neg',
 'neg',
 'neg',
 'pos',
 'neg',
 'neg',
 'neg',
 'neg',
 'neg',
 'pos',
 'pos',
 'pos',
 'pos',
 'neg',
 'pos',
 'neg',
 'neg',
 'neg',
 'neg',
 'pos',
 'neg',
 'neg',
 'pos',
 'neg',
 'neg',
 'neg',
 'neg',
 'neg',
 'pos',
 'pos',
 'pos',
 'pos',
 'pos',
 'pos',


In [50]:
ids = np.arange(10000)

In [51]:
final_matrix = np.stack((ids,y_pred), axis = 1)

In [52]:
df = pd.DataFrame(final_matrix, columns=['Id','label'])

In [53]:
df

Id label
0        0   neg
1        1   neg
2        2   neg
3        3   pos
4        4   pos
...    ...   ...
9995  9995   neg
9996  9996   pos
9997  9997   pos
9998  9998   pos
9999  9999   neg

[10000 rows x 2 columns]

In [54]:
# from google.colab import files
df.to_csv('last.csv', index=False) 
# files.download('final.csv')